"""Addedthe image column

Revision ID: 83e41e9043ee
Revises: 11d96e5064f5
Create Date: 2022-05-15 22:54:21.051191

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83e41e9043ee'
down_revision = '11d96e5064f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('image_file', sa.String(length=100), nullable=True))
    op.drop_column('users', 'image')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('image', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('users', 'image_file')
    # ### end Alembic commands ###
